version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ORDER_MANAGEMENT_SYSTEM
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:7.2
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - app-network

  gateway-service-app:
    build:
      context: ./GatewayService
      dockerfile: Dockerfile
    container_name: gateway-service-app
    environment:
      - JWT_SECRET=YXNkZnNha2pmc2FrZmphc2tmamFzZGtqYXNkbGtqZmFzZGtmamtzZA==
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - auth-service-app
      - user-service-app
    networks:
      - app-network

  user-service-app:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    container_name: user-service-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ORDER_MANAGEMENT_SYSTEM?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT=0
      - SPRING_DATASOURCE_CONNECTION_TIMEOUT=50000
    depends_on:
      - mysql
    networks:
      - app-network

  auth-service-app:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: auth-service-app
    expose:
      - "8081"
    environment:
      - JWT_SECRET=YXNkZnNha2pmc2FrZmphc2tmamFzZGtqYXNkbGtqZmFzZGtmamtzZA==
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ORDER_MANAGEMENT_SYSTEM?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT=0
      - SPRING_DATASOURCE_CONNECTION_TIMEOUT=50000
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - mysql
    networks:
      - app-network

  order-service-app:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    container_name: order-service-app
    expose:
      - "8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ORDER_MANAGEMENT_SYSTEM?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT=0
      - SPRING_DATASOURCE_CONNECTION_TIMEOUT=50000
    depends_on:
      - mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge